excluded: # 执行时忽略的路径
    - Pods
disabled_rules: # 执行时排除掉的规则
    - line_length
    - trailing_whitespace
    - identifier_name
    - trailing_newline
    - comma
    - colon
    - mark
    - file_length
    - multiple_closures_with_trailing_closure
    - force_cast
    - cyclomatic_complexity
    - closure_parameter_position
    - function_body_length
    - type_body_length
    - function_parameter_count
    - block_based_kvo
