platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

workspace 'App.xcworkspace'

def project_pods
  pod 'SnapKit'
  pod 'SwiftLint'
end

def network_pods
  pod 'Alamofire'
  pod 'HandyJSON'
end

target 'App' do

  project_pods
  network_pods

end
