platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

workspace 'App.xcworkspace'

def project_pods
  pod 'SnapKit'
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
end

def network_pods
  pod 'Alamofire'
  pod 'HandyJSON'
end

target 'App' do

  project_pods
  network_pods

end

target 'XSBase' do
  
  project 'XSBase/XSBase.xcodeproj'
  
  project_pods
end
